whitelist_ips:
  - 192.168.1.10

whitelist_domains:
  - allowed.internal

blocked_ips:
  - 10.0.0.5

blocked_domains:
  - internalmalware.site

external_blocklists:
  - type: ip
    url: https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_level1.netset
  - type: ip
    url: https://blocklist.greensnow.co/greensnow.txt
  - type: domain
    url: https://phishing.army/download/phishing_army_blocklist.txt
  - type: domain
    url: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

external_allowlists:
  - type: ip
    url: https://example.com/allowed_ips.txt
  - type: domain
    url: https://example.com/allowed_domains.txt

features:
  owasp_protection: true
