squid:
  port: 3128
  allowed_ips:
    - 192.168.1.0/24
    - 10.0.0.1
  ip_blacklist_sources:
    - ip_blacklist1.txt  # Local file or replace with a URL
  dns_blacklist_sources:
    - dns_blacklist1.txt  # Local file or replace with a URL
  owasp_protection: true
  block_vpn: true
  block_tor: true
  block_cloudflare: true
  block_aws: true
  block_microsoft: true
  block_google: true
  vpn_ip_sources:
    - https://raw.githubusercontent.com/X4BNet/lists_vpn/main/ipv4.txt  # Public VPN IP list
  tor_ip_sources:
    - https://check.torproject.org/torbulkexitlist  # Tor exit node list
  cloudflare_ip_sources:
    - https://www.cloudflare.com/ips-v4  # Cloudflare IPv4 ranges
    - https://www.cloudflare.com/ips-v6  # Cloudflare IPv6 ranges
  aws_ip_sources:
    - https://ip-ranges.amazonaws.com/ip-ranges.json  # AWS IP ranges
  microsoft_ip_sources:
    - https://download.microsoft.com/download/7/1/D/71D86715-5596-4529-9B13-DA13A5DE5B63/ServiceTags_Public_20240205.json  # Microsoft Azure IP ranges
  google_ip_sources:
    - https://www.gstatic.com/ipranges/goog.json  # Google Cloud IP ranges
  logging:
    access_log: /var/log/squid/access.log
    cache_log: /var/log/squid/cache.log
    log_format: combined
  cache:
    enabled: true
    cache_type: ufs
    cache_dir: /var/spool/squid
    cache_size: 10000
    max_object_size: 512 MB
