squid:
  port: 3128
  cache_size: 500 # MB
  cache_dir: /var/spool/squid
  external_dns:
    enabled: true
    resolvers: ["8.8.8.8", "8.8.4.4"]
  https:
     enabled: true
     port: 3129
     ssl_cert: /data/ssl/squid.pem
     ssl_key: /data/ssl/squid.key
blocklists:
  dns:
    enabled: false
    sources: []
    local_file: "/data/blocklists/dns_blocklist.txt"

  ip:
    enabled: false
    sources: []
    local_file: "/data/blocklists/ip_blocklist.txt"

whitelist:
  enabled: false
  ips: []
  domain_allowlist: []

network:
  allow_direct: false

authentication:
  enabled: true
  users:
    - username: "testuser"
      password: "testpassword"
  method: "basic"
