squid:
  port: 3128
  allowed_ips:
    - 192.168.1.0/24
    - 10.0.0.1
  ip_blacklist_sources:
    - ip_blacklist1.txt
  dns_blacklist_sources:
    - dns_blacklist1.txt
  owasp_protection: true
  block_vpn: true
  block_tor: true
  block_cloudflare: true
  block_aws: true
  block_microsoft: true
  block_google: true
  logging:
    access_log: /var/log/squid/access.log
    cache_log: /var/log/squid/cache.log
    log_format: combined
  cache:
    enabled: true
    cache_dir: /var/spool/squid
    cache_size: 10000
    max_object_size: 512 MB
  authentication:
    enabled: false
  time_restrictions:
    - name: work_hours
      days: MTWHF
      time: 09:00-17:00
      action: allow
  custom_acls:
    - name: block_social_media
      type: dstdomain
      values:
        - facebook.com
        - twitter.com
      action: deny
