version: "3.8"
services:
  squid-proxy:
    build: .
    ports:
      - "3128:3128"
      - "3129:3129"
    volumes:
      - ./data:/data
    environment:
      SQUID_PORT: "3129"
      SQUID_CACHE_SIZE: "600"
      SQUID_EXTERNAL_DNS_ENABLED: "false"
      SQUID_HTTPS_ENABLED: "true"
      SQUID_HTTPS_PORT: "3130"
      BLOCKLISTS_DNS_ENABLED: "false"
      BLOCKLISTS_IP_ENABLED: "false"
      WHITELIST_ENABLED: "true"
      WHITELIST_IPS: "192.168.1.1,10.0.0.1"
      WHITELIST_DOMAIN_ALLOWLIST: "test.com,test2.net"
      NETWORK_ALLOW_DIRECT: "false"
      AUTHENTICATION_ENABLED: "true"
      AUTHENTICATION_USERS: "testuser:newpassword,testuser2:password2"
