version: '3.8'

services:
  proxy:
    build:
      context: .
      dockerfile: docker/Dockerfile.squid
    ports:
      - "3128:3128"
    volumes:
      - ./config/squid/squid.conf:/etc/squid/squid.conf
      - ./config/blacklists:/etc/squid/blacklists
      - squid_cache:/var/cache/squid
      - squid_logs:/var/log/squid
    restart: unless-stopped
    networks:
      - proxy-network

  dashboard:
    build:
      context: .
      dockerfile: docker/Dockerfile.dashboard
    ports:
      - "8080:80"
    volumes:
      - ./src/dashboard:/app
    depends_on:
      - proxy
    environment:
      - PROXY_HOST=proxy
      - PROXY_PORT=3128
    restart: unless-stopped
    networks:
      - proxy-network

volumes:
  squid_cache:
  squid_logs:

networks:
  proxy-network:
    driver: bridge