name: Test Squid Configuration Generation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests

      - name: Generate Squid configuration
        run: |
          python generate_squid_conf.py
          cat squid.conf

      - name: Build Docker image
        run: |
          docker build -t squid-test .

      - name: Validate Squid configuration
        run: |
          docker run --rm \
            -v $(pwd)/squid.conf:/etc/squid/squid.conf \
            squid-test \
            squid -k parse
