name: Test Squid Configuration Generation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: "3.9"
  DOCKER_IMAGE_NAME: "squid-test"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Squid configuration
        run: |
          python generate_squid_conf.py
          echo "Generated squid.conf:"
          cat squid.conf

      - name: Validate Squid configuration file
        run: |
          if [ ! -f squid.conf ]; then
            echo "Error: squid.conf file not found!"
            exit 1
          fi
          echo "squid.conf file exists and is ready for testing."

      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_NAME }} .

      - name: Validate Squid configuration in Docker
        run: |
          docker run --rm \
            -v $(pwd)/squid.conf:/etc/squid/squid.conf \
            ${{ env.DOCKER_IMAGE_NAME }} \
            squid -k parse
